# Generated by Django 2.2.7 on 2019-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=200)),
                ('Images', models.CharField(max_length=200)),
            ],
        ),
    ]
