# Generated by Django 3.0 on 2019-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=50)),
                ('Result', models.CharField(max_length=50)),
                ('HomeTeam', models.CharField(max_length=50)),
                ('HImage', models.CharField(max_length=50)),
                ('Goal', models.CharField(max_length=50)),
                ('AwayTeam', models.CharField(max_length=50)),
                ('AImage', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=10)),
                ('Tournament', models.CharField(max_length=100)),
            ],
        ),
    ]
